services:
  us-52w-hl-stock:
    image: ghcr.io/liante0904/52w-stock-pdf-bot:latest
    container_name: us-52w-hl-stock
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pdf:/app/pdf
    working_dir: /app/us
    command: ["python", "app.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - SCHEDULE_HOUR=15
      - SCHEDULE_MINUTE=40
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - PDF_SAVE_DIR=/app/pdf

  jp-52w-hl-stock:
    image: ghcr.io/liante0904/52w-stock-pdf-bot:latest
    container_name: jp-52w-hl-stock
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pdf:/app/pdf
    working_dir: /app/jp
    command: ["python", "app.py"]
    environment:
      - SCHEDULE_HOUR=16
      - SCHEDULE_MINUTE=00
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - PDF_SAVE_DIR=/app/pdf

  kr-52w-hl-stock:
    image: ghcr.io/liante0904/52w-stock-pdf-bot:latest
    container_name: kr-52w-hl-stock
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pdf:/app/pdf
    working_dir: /app/kr
    command: ["python", "app.py"]
    environment:
      - SCHEDULE_HOUR=16
      - SCHEDULE_MINUTE=00
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Seoul
      - PDF_SAVE_DIR=/app/pdf
